--- # Installing Httpd Server and Starting it
-   hosts: master
    tasks:
    - name: Install httpd server on centos
      yum:
        name: httpd
        state: latest
      notify:
       - startservice
    handlers:
    - name: startservice
      service:
         name: httpd
         state: restarted
         enabled: yes
