--- # Debugging
-   hosts: '{{ myHosts }}'
    vars:
        myHosts: all
        pkg: telnet
    tasks:
    - name: Install telnet server on centos
      yum:
        name: '{{ pkg }}'
        state: latest
      register: result
    - debug: var=result
